name = "ak4duy-blog-polls"
main = "workers/blog-polls.js"
compatibility_date = "2026-05-26"

routes = [
  { pattern = "api.akaduy.dev/blog-polls/*", zone_name = "akaduy.dev" },
  { pattern = "api.akaduy.dev/health", zone_name = "akaduy.dev" }
]

[[d1_databases]]
binding = "BLOG_POLLS_DB"
database_name = "blog-polls"
database_id = "87fcd75a-f5f3-4a33-8427-dc092846b83c"
